# Generated by Django 3.1.7 on 2021-02-28 23:12

from django.db import migrations, models
import django.db.models.deletion
import menu.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[menu.validators.validate_not_past])),
                ('options', models.JSONField(validators=[menu.validators.validate_list_of_strings])),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('to_be_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('employee_slack_id', models.CharField(max_length=256)),
                ('employee_real_name', models.CharField(max_length=256)),
                ('employee_channel', models.CharField(max_length=256, null=True)),
                ('date', models.DateField()),
                ('selected', models.CharField(max_length=256, null=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('sent', models.DateTimeField(null=True)),
                ('fulfilled', models.DateTimeField(null=True)),
                ('ts', models.CharField(max_length=256, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.menu')),
            ],
        ),
    ]
