# Generated by Django 3.1.7 on 2021-03-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', 'created']},
        ),
    ]
